### ISSUE TITLE
Percentags include missing data

### ISSUE THREAD

**Issue by edrill** [MSKCC-Epi-Bio/gnomeR#130]
Hi, Using gnomeR for a project (thanks for your efforts!) - and noticed that the percentages generated by the gen.summary function use all the samples in the matrix as the denominator rather than only the ones are sequenced for those genes. (This is in the context where you have data from multiple IMPACT panels.) So even if I filter at 5%, if I have genes that are sequenced in only a small number of patients, it will show percentages lower than 5%.

Relatedly, it would be great to have an option to filter out genes that are sequenced in less than some threshold of samples. 

Let me know if you want specific examples.
Thank you!

**Comment by AxelitoMartin** [comment]
Fixed both in gen.summary and uni.cox (also added na filtering via na.filt)
