### ISSUE TITLE
Mislabeling of legend in oncoprint

### ISSUE THREAD

**Issue by edrill** [MSKCC-Epi-Bio/gnomeR#131]
Following the vignette, I run the command `plot_oncoPrint(gen.dat = select(bmat, all_of(genes)))`. I get the following messages in console:
**All mutation types: MUT, AMP, DEL.
Following `at` are removed: FUS, MIS, because no color was defined for them.
Following `at` are removed: FUS, MIS, because no color was defined for them.
Following `at` are removed: FUS, MIS, because no color was defined for them.**

Attaching resulting oncoprint:
![oncoprint](https://user-images.githubusercontent.com/17861122/135204051-2c8d7fba-a152-4740-ae5e-709b2ba4a60d.JPG)

The correct labeling should be:
Blue square = Deletion
Red square = Amplification
Green line = Mutation

I ran the above code with both the regular and development versions of gnomeR.

Thank you!

**Comment by edrill** [comment]
Relatedly,  it would be great if there is an option to include Variant Classification information in the Oncoprint (e.g. Nonsense Mutation, Missense Mutation, etc.), as is done in the cBioPortal version of Oncoprint.

**Comment by carokos** [comment]
I'm running into the same problem as @edrill -- 

Here's a simple, reproducible example of what's happening.  It looks like the actual plot is correct, but the legend is wrong.

``` r
mat = matrix(sample(c(0,0,0,0,0,1), 100, replace = TRUE),
             ncol = 10)
colnames(mat) = c(paste0(rep("gene", 5), 1:5),
                  paste0(rep("gene", 2), 1:2, ".Amp"),
                  paste0(rep("gene", 3), 1:3, ".Del"))
rownames(mat) = paste0(rep("sample", 10), 1:10)
mat
#>          gene1 gene2 gene3 gene4 gene5 gene1.Amp gene2.Amp gene1.Del gene2.Del
#> sample1      0     0     1     0     0         0         0         0         0
#> sample2      0     0     1     0     0         0         0         1         0
#> sample3      0     0     0     0     0         0         0         0         0
#> sample4      1     0     0     0     1         1         1         1         0
#> sample5      0     0     0     0     0         1         1         0         0
#> sample6      0     0     0     0     0         0         0         0         1
#> sample7      0     0     0     0     0         0         0         0         0
#> sample8      0     0     1     0     1         0         0         0         0
#> sample9      0     0     0     0     0         0         0         0         0
#> sample10     0     0     0     0     0         0         0         0         0
#>          gene3.Del
#> sample1          0
#> sample2          0
#> sample3          1
#> sample4          0
#> sample5          0
#> sample6          1
#> sample7          0
#> sample8          0
#> sample9          0
#> sample10         0

gnomeR::plot_oncoPrint(gen.dat = mat)
#> Registered S3 method overwritten by 'GGally':
#>   method from   
#>   +.gg   ggplot2
#> Warning in dat.oncoPrint(gen.dat, clin.dat): All genetic components were not
#> binary. Those which weren't will be removed
#> All mutation types: MUT, DEL, AMP.
#> Following `at` are removed: FUS, MIS, because no color was defined for
#> them.
#> Following `at` are removed: FUS, MIS, because no color was defined for
#> them.
#> Following `at` are removed: FUS, MIS, because no color was defined for
#> them.
```

![](https://i.imgur.com/IsprJRf.png)

<sup>Created on 2022-03-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by karissawhiting** [comment]
@carokos @edrill Thanks for filing this, and sorry it hasn't been addressed. Oncoprints are complex and hard to support/maintain, so we've decided to remove this for now and plan to move it to its own package in the future. For now, this functionality will be deprecated in the package (you still can download/use the old version of the package with the function if needed for old projects).

Thanks for bearing with us!
