### ISSUE TITLE
Create Vignette that uses {cbioportalR} to pull data and {gnomeR} to process data

### ISSUE THREAD

**Issue by karissawhiting** [MSKCC-Epi-Bio/gnomeR#145]
We should have a case study vignette that uses data pulled directly from cBioPortal in {gnomeR} functions. See {cbioportalR} vignette for instructions on how to pull data: https://github.com/karissawhiting/cbioportalR

**Comment by akriti21** [comment]
I am interested in this one

**Comment by karissawhiting** [comment]
@akriti21 Great! `usethis::use_vignette()` can be helpful to get started.

One thing to note is that data pulled from {cbioportalR} has different formats/column names than data required in `gnomeR::binary_matrix()`:

- For mutation data, I think it's just differences in column names. For example, {gnomeR} requires `Tumor_Sample_Barcode` as the sample id column and {cbioportalR} returns the col `sampleId`. See `gnomeR::mut` example dataset for needed gnomeR data format. (Eventually, it could be useful to write a helper function that renames {cbioportalR} data so it can be used in {gnomeR})
- For cna data, the data will need to be reformatted. See `gnomeR::cna` for the necessary format. I wrote the function `gnomeR::reformat_cna` to help reformat this, but haven't tested it yet. 
- Not sure what fusion data aspect may require yet. See `gnomeR::fusion` for the necessary format

Thanks!

**Comment by akriti21** [comment]
this is super helpful! I am focusing on mutation data first

**Comment by karissawhiting** [comment]
@akriti21 at your suggestion, I think we should have a short section outlining the basic differences between API data and traditional cBioPortal data. basic things like colnames differences is fine for this and we can cite https://docs.cbioportal.org/5.1-data-loading/data-loading/file-formats

**Comment by akriti21** [comment]
sure Karissa.. i compared the variables for mutation data..for API there were 45 variables and for cBioportal, 30. i dont think 12 of these 30 variables exist in the API data. i tried to match the other 18 variables.. 
[Data dictionaries.xlsx](https://github.com/MSKCC-Epi-Bio/gnomeR/files/8445747/Data.dictionaries.xlsx)

**Comment by karissawhiting** [comment]
Hi @akriti21 ! I think a lot of this is still relevant and the vignette you started in your PR is still usable, though may need some updates since the underlying package code has changed a bit. 

Differences in data pulled from different sources is less of an issue now because we've build some functionality to automatically rename data as needed. I think we can not spend too much time in the vignette talking about the differences now. 

I think this vignette should:

1. Pull data from cBioPortal (see [https://github.com/karissawhiting/cbioportalR package for](https://www.karissawhiting.com/cbioportalR/)) for details
2. Explain about CNA data formats a bit as these can be wide or long (let's discuss this more on Thursday)
3. Focus on the `crete_gene_binary()` function and discuss the different arguments in it

Let's call it the "Data Processing" vignette.

**Comment by akriti21** [comment]
Thanks Karissa, this is very clear and helpful. 
Yes, we can chat tomorrow about the 2 formats. And I will rename the vignette I have and start updating it tomorrow.

**Comment by karissawhiting** [comment]
#190 Closed
