### ISSUE TITLE
Add IMPACT Heme panel (IH3 & IH4)

### ISSUE THREAD

**Issue by karissawhiting** [MSKCC-Epi-Bio/gnomeR#149]
talk to @edrill about this.

**Comment by karissawhiting** [comment]
- add to gnomeR::impact_alias_table (vetted impact aliases)
- compare against other IMPACT gene names to make sure same aliases are being used
- make sure it works in specify_panel functionality

**Comment by jalavery** [comment]
IH3 = IMPACT-HEME-400
IH4 = IMPACT-HEME-468

**Comment by jalavery** [comment]
- Added the panel to the alias table 
- Tested the specify_panel functionality (when specify_panel = "impact", NAs are properly annotated; when specify_panel = "IMPACT-HEME-400", NAs are properly annotated)
- @karissawhiting Could we chat about # 2 in your list above? not sure how to compare the aliases 

Submitted a PR so you can easily see what I changed so far, but it isn't ready for review just yet!
