### ISSUE TITLE
Edit pathway annotation using gene-level data in `add_pathways()` function

### ISSUE THREAD

**Issue by carokos** [MSKCC-Epi-Bio/gnomeR#167]
The oncogenic signaling pathways taken from the paper can only be annotated using an alteration-level matrix.  
We should prevent users from annotating the default pathways with a gene-level alteration matrix, but keep the functionality for user who have a custom pathway (i.e. for exploratory analyses, or for other pathways with less-strict definitions).

**Comment by karissawhiting** [comment]
@carokos if you have time this hackathon, could you double check this functionality now that some of the underlying code has changed? Also we need to maybe update unit tests (internal package data has changed)

**Comment by karissawhiting** [comment]
Now in #251
