### ISSUE TITLE
Check column names of input df and allow create_binary_matrix() to accept maf, api or snakecase version of maf names

### ISSUE THREAD

**Issue by karissawhiting** [MSKCC-Epi-Bio/gnomeR#171]
We need to improve handling of column names in `create_binary_matrix()`. The function should by default support: traditional maf names (see link below), lower snakecase version of maf names, and API column names. 

This needs to be done for mutation (maf), cna, and structural variant data eventually but we will start with mutation (maf). 

1. Look at [maf data specifications](https://docs.gdc.cancer.gov/Data/File_Formats/MAF_Format/) and compare to API specifications. You can pull API data using cbioportalR. **Make sure you install the development version of the package**

```r 
library(cbioportalR)
set_cbioportal_db("msk")
msk_2017 <- get_genetics_by_study("msk_impact_2017")

ss <- available_samples("msk_impact_2017")
h_ss <- head(ss, n = 100)

msk_2017 <- get_genetics_by_sample(sample_id = h_ss$sampleId)
msk_2017$mutation
```
3. Make a table for internal documentation of the column names and how they match up between maf and API (double check cbioportal docs as well regarding their data formats). (See #158 and maybe integrate the table directly in this vignette eventually)
5. Discuss above table and decide what level of flexibility we want to accept with column names 
6. Create function that checks and guesses column names before passing the data into `create_binary_matrix()`
7. Decide on minimum columns needed and which columns support which `create_binary_matrix()` arguments. Improve errors/messaging for when certain columns are missing (e.g. variant type = "germline")

**Comment by hfuchs5** [comment]
Here is the table with MAF variable names compared to the API format that came from cbioportalR: [MAF vs API column names.xlsx](https://github.com/MSKCC-Epi-Bio/gnomeR/files/9455237/MAF.vs.API.column.names.xlsx)

**Comment by karissawhiting** [comment]
awesome! Can you add this to the `data-raw` folder of the package along with a script (can be empty for now) called `data-schema.R`. 

I'm thinking we can use `data-schema.R` to read in a version of this table into R and turn it into an internal dataset within the package and refer to it in functions that need to resolve names.

Thanks @hfuchs5 !

**Comment by hfuchs5** [comment]
I uploaded these two files! I wasn't sure if you went ahead and finished the function because you showed us something during the training that renamed the columns. Lmk if you want me to go forward with the data-schema.R file.

**Comment by karissawhiting** [comment]
We may be able to add some additional here. The below names are from the following example from `prad_msk_2019 study`. I think the tumor alt count/ tumor ref count may be in both and maybe alo mutation status? We can add to `accepted-column-names.csv` if so. 

```r 
set_cbioportal_db("msk")
gen <- get_genetics_by_study(study_id = "prad_msk_2019")

gen$mutation
```

Some column names I found: 

[1] "uniqueSampleKey"        "uniquePatientKey"      
 [5] "molecularProfileId"           "studyId"               
 [9] "center"                 "mutationStatus"        "tumorAltCount"         
[13] "tumorRefCount"          "normalAltCount"         "normalRefCount"         "start_position"        
[21] "functionalImpactScore"  "fisValue"               "linkXvar"               "linkPdb"               
[25] "linkMsa"                "ncbi_build"             "variant_type"           "keyword"               
[29] "chromosome"             "allele"                 "refseqMrnaId"           "x"                     
[33] "x_2"

**Comment by karissawhiting** [comment]
Let's write some tests for this as well checking what changes the data has undergone before and after using the function

**Comment by karissawhiting** [comment]
Completed in #184
