### ISSUE TITLE
Error returned for binmat oncokb = TRUE when cbioportalR updated

### ISSUE THREAD

**Issue by slb2240** [MSKCC-Epi-Bio/gnomeR#173]
I updated my {cbioportalR} package to the version on CRAN. Now when I run binmat() using the data pulled from {cbioportalR} and try to annotate for oncokb = TRUE, I get the following error: Error in py_call_impl(callable, dots$args, dots$keywords) : 
KeyError: False

Any ideas on how to fix this? Thank you!!!

**Comment by karissawhiting** [comment]
All oncoKB functionality has now been moved to a separate package: https://github.com/karissawhiting/oncokbR
