### ISSUE TITLE
make `tbl_genomic` an official 'gtsummary' table 

### ISSUE THREAD

**Issue by michaelcurry1123** [MSKCC-Epi-Bio/gnomeR#174]
- [x] Do something about environments idk @michaelcurry1123 knows.
- [x] Maybe append a class? (Although maybe do this later
- [x] Remove all styling from internal function
- [x] Update examples and tests to use new example data (depends on #175 )
- [x] Review unit tests and make sure everything important is being tested
- [x] Maybe rewrite gene summary calculations (pre-thresholding) to be faster by using base R? 
- [x] Work with whoever is working on the vignette to add a section about this
- [x] #197

**Comment by michaelcurry1123** [comment]
Dan said to make it an official 'gtsummary' table all you need to do is append your own class to the front of the class like so:
```class(df_tbl) <- c("tbl_genomic", class(df_tbl))```. Then from here if we wanted to create a tbl_genomic method we can and the classes will be in the proper order. I can add it to the function tbl_genomic().

**Comment by michaelcurry1123** [comment]
might want to remove bold_labels and add_overall from internals of tbl_genomic and just allow the user to specify.

**Comment by karissawhiting** [comment]
@michaelcurry1123 can we close this?

**Comment by michaelcurry1123** [comment]
@karissawhiting  yes we can close!
