### ISSUE TITLE
Create common internal function for use in .mutations_gene_binary(), .cna_gene_binary(), and .fusions_gene_binary()

### ISSUE THREAD

**Issue by karissawhiting** [MSKCC-Epi-Bio/gnomeR#177]
These three internal data processing functions share a lot of code that could be separated out into its own internal function. 

For example, the following could be an internal function for populating resulting matricies.

```r


  # create empty data.frame to hold results -----
  mut <- as.data.frame(matrix(0L, nrow=length(samples),
                              ncol=length(unique(mutation$hugo_symbol))))

  colnames(mut) <- unique(mutation$hugo_symbol)
  rownames(mut) <- samples

  # populate matrix
  for(i in samples){
    genes <- mutation$hugo_symbol[mutation$sample_id %in% i]
    if(length(genes) != 0) {
      mut[match(i, rownames(mut)), match(unique(as.character(genes)), colnames(mut))] <- 1
      }
  }

```

**Comment by hfuchs5** [comment]
Very close to being done with this, just need to figure out a way to bind the separate cna .Del and .Amp datasets together and output. SV, mutations, and a version for reformat_cna are all working.

**Comment by karissawhiting** [comment]
1.If .Del is known 0 or 1, then .Amp can also be input as 0 (not NA)
2. Same above for fusions/CNA/Mutation binding. They wouldnt test just one type of alteration for a panel
3. rm_empty- Karissa to review, for now Mike is only returning gene columns where there is at least 1 event
4. Now it returns a data frame with no row names (sample ID is a column)
