### ISSUE TITLE
Review package checks and iClusterPlus errors in github actions

### ISSUE THREAD

**Issue by karissawhiting** [MSKCC-Epi-Bio/gnomeR#198]

**Comment by michaelcurry1123** [comment]
I added code to download Bioconductor packages and added it to the CMD-check action I also updated all versions of the checkouts to v2 from v1, only the Bioconductor code is set to v1:
link to Bioconductor code: https://github.com/grimbough/bioc-actions/tree/v1/setup-bioc
we will need to monitor the version of Bioconductor it is set at 3.15 but will change overtime

**Comment by michaelcurry1123** [comment]
all checks are on version 2 instead of version 1 now and all pass
