### ISSUE TITLE
Check other functions that may be affected by sample ID column

### ISSUE THREAD

**Issue by karissawhiting** [MSKCC-Epi-Bio/gnomeR#201]
Related  to changes in #177

**Comment by karissawhiting** [comment]
- tbl_genomic
- sumamarize_by_gene
- add_pathways
- others??

**Comment by michaelcurry1123** [comment]
@karissawhiting 
add_pathways identifies columns for .mut with regular expressions using `stringr` this might mess up the function because it identified sample_id as a mut_col, should be an easy fix by adding in sample_id to the `str_detect()`

  ```
all_cols <- colnames(gene_binary)
  mut_cols <- !(str_detect(all_cols, ".Amp|.Del|.fus|.cna"))


      custom_pathways <- purrr::map(custom_pathways, function(x) {
        x[!str_detect(x, ".Amp|.Del|.fus|.cna")] <-
          paste0(stringr::str_trim(
            x[!str_detect(x, ".Amp|.Del|.fus|.cna")]), ".mut")

        unique(x)

        } )
```

**Comment by michaelcurry1123** [comment]
@karissawhiting @hfuchs5  I am going to make another pr/branch for this after we merge in the changes from internal_gen_bin_tidy bc those are the changes that will affect this
