### ISSUE TITLE
`purrr::when()` will be depreciated

### ISSUE THREAD

**Issue by michaelcurry1123** [MSKCC-Epi-Bio/gnomeR#203]
`purrr::when()` will be depreciated, we will need to update all functions that have `purrr::when()` to something else.... eventually

**Comment by michaelcurry1123** [comment]
ctrl + shift + F will open a find command that will look for a text string in all files in a directory, easy way to find purrr::when

**Comment by hfuchs5** [comment]
To ask in meeting:


 "data.frame" = {

           specify_panel %>%
             purrr::when(
               any(is.na(specify_panel$panel_id)) ~ cli::cli_abort("Some {.field panel_id} values in {.code sample_panel_pair} df are {.code NA}. Please explicitely indicate {.code no} for those samples instead if you wish to skip annotating these."),
               length(setdiff(c(specify_panel$panel_id), c(gene_panels$gene_panel, "no"))) > 0 ~
                           cli::cli_abort("Panels not known: {.val {setdiff(c(specify_panel$panel_id), c(gene_panels$gene_panel, 'no'))}}. See {.code  gnomeR::gene_panels} for known panels, or skip annotation with {.code specify_panel = 'no'} or indicating {.code 'no'} for those samples in {.field panel_id} column of sample_id-panel_id pair data frame"),
                         TRUE ~ .)}

}

**Comment by karissawhiting** [comment]
Updated #238
