### ISSUE TITLE
error message should be removed or changed `summarize_by_gene()`?

### ISSUE THREAD

**Issue by michaelcurry1123** [MSKCC-Epi-Bio/gnomeR#204]
these error messages state ids will be found in `rownames` but that isn't true anymore from `create_gene_binary()` should these be changed?

  ```
if (!is.data.frame(gene_binary)) {
    cli::cli_abort("{.code gene_binary} must be a data.frame with sample ids as {.code rownames(gene_binary)}")
  }

  if (!("sample_id" %in% names(gene_binary))) {
    gene_binary <- rownames_to_column(gene_binary, var = "sample_id")
  }
```

**Comment by karissawhiting** [comment]
Can we do a quick search for other places in the package where this might occur?

**Comment by michaelcurry1123** [comment]
the other two places this is found is in tbl_genomic and add_pathways. but in add pathways is it commented out already.

**Comment by karissawhiting** [comment]
remove rownames errors and add check for sample_id column in tbl_genomic(), add_pathways()
