### ISSUE TITLE
helper function to recode old fusion format to new format

### ISSUE THREAD

**Issue by hfuchs5** [MSKCC-Epi-Bio/gnomeR#229]
- old format has two lines for each event (say APC-TP53) would have one line for the first and another for the second gene
- new format has two columns and one row per event
- need to think of a way to read through the column names and see if `site1_hugosymbol` & `site2_hugosymbol` exist or not

*NOTE: When pulling GENIE data from `{genieBPC}` or `{synapser}` the old format is used. Pulling down from cBioPortal gives new format.

**Comment by hfuchs5** [comment]
look into regex function to split fusion at " " (ex: TERT-APC fusion) without the fusion at the end.

**Comment by karissawhiting** [comment]
Akriti to update documentation and write tests for this new function.
