### ISSUE TITLE
dat_oncoprint() function

### ISSUE THREAD

**Issue by slb2240** [MSKCC-Epi-Bio/gnomeR#233]
- dat_oncoprint() function has been commented out in latest gnomeR release. Is it possible to add back in? Thank you!!

**Comment by karissawhiting** [comment]
Hi @slb2240! We've decided we can't support oncoprints in {gnomeR} at this time. They were too buggy and we weren't able to properly maintain them. 

Here is a link to the old code that was in this package for oncoprints, including `dat_oncoprint()`: https://github.com/MSKCC-Epi-Bio/gnomeR/blob/ad38975e4de4342d741d7b5b4cca1970817f5ec1/R/oncoprint.R 

Eventually we have plans to build this functionality out into its own package. Hopefully the code above will work for now, and we'll keep you updated on progress with the oncorpint package!

(@hfuchs5)
