### ISSUE TITLE
Potential option to make pathways() mutually exclusive

### ISSUE THREAD

**Issue by hfuchs5** [MSKCC-Epi-Bio/gnomeR#248]
Results are slightly different from the version I used in my analysis 

CDKN2A appears in both the p53 and cell cycle pathways. My analysis removed CDKN2A from the p53 pathway to keep all pathways mutually exclusive.  Maybe this should be an option in case people want mutually exclusive pathways as we did? (Thinking more, they could define a custom pathway to get around this, though it might be less user friendly that way…)

**Comment by karissawhiting** [comment]
Since we don’t have a good way to chose which pathway the repeated gene would go on, for now we will rely on `custom_pathway` to achieve this.
