### ISSUE TITLE
count_pathways_by() has confusing documentation and functionality regarding gene level vs. alt level

### ISSUE THREAD

**Issue by hfuchs5** [MSKCC-Epi-Bio/gnomeR#251]
“Assuming any gene in `custom_pathway` without suffix `Amp|.Del|.fus|.cna` is specifically a mutation in that pathway. CNA and fusions will not be counted (e.g. TP53.Del). To control this behavior, see argument `count_pathways_by`” – what does this mean? 

Context: I have two simple custom pathways 

my_path <- c("BRAF", "NRAS", "NF1") 

my_path2 <- c("CDKN2A.Del", "TERT.Amp", "PTEN.Del") 

Does this mean that my_path will be treated as mutations only, but my_path2 will be treated at the alteration level (especially since the alteration types are specified)? 

How do we specifiy if we want the mutation only? (I tried my_path1 <- c(“BRAF.mut”, “NRAS.mut”, “NF1.mut”), but the results are completely different from my_path.)

**Comment by karissawhiting** [comment]
Thanks for pointing this out, I agree the messaging is confusing here.  

The output of the function is entirely dependent on the `count_pathways_by` argument in this function and not how you input the genes. By default, pathways are counted on the alteration-level and a gene name without any suffix is counted as a mutation. For example in the below, the BRAF.Del is not counted In the pathway by default. 

``` r
library(gnomeR)
library(tibble)

bm <- tribble(
  ~sample_id, ~BRAF, ~BRAF.Del, ~NRAS.Del, ~NF1, 
  "xx",        0,       0,        1,        0,
  "yy",        1,       0,        0,        0,
  "zz",        0,       1,        0,        0
)

bm %>%
  add_pathways(
    pathways = NULL,
    custom_pathways = c("BRAF", "NRAS", "NF1"))
#> Assuming any gene in `custom_pathway` without suffix `Amp|.Del|.fus|.cna` is
#> specifically a mutation in that pathway. CNA and fusions will not be counted
#> (e.g. TP53.Del). To control this behavior, see argument `count_pathways_by`
#> # A tibble: 3 × 6
#>   sample_id  BRAF BRAF.Del NRAS.Del   NF1 pathway_custom
#>   <chr>     <dbl>    <dbl>    <dbl> <dbl>          <dbl>
#> 1 xx            0        0        1     0              0
#> 2 yy            1        0        0     0              1
#> 3 zz            0        1        0     0              0
```

If we set `count_pathways_by = “gene”` however, the BRAF.DEL and also NRAS.Del will be counted towards the pathway: 

``` r
library(gnomeR)
library(tibble)

bm <- tribble(
  ~sample_id, ~BRAF, ~BRAF.Del, ~NRAS.Del, ~NF1, 
  "xx",        0,       0,        1,        0,
  "yy",        1,       0,        0,        0,
  "zz",        0,       1,        0,        0
)

bm %>%
  add_pathways(
    pathways = NULL,
    custom_pathways = c("BRAF", "NRAS", "NF1"), 
    count_pathways_by = "gene")
#> # A tibble: 3 × 6
#>   sample_id  BRAF BRAF.Del NRAS.Del   NF1 pathway_custom
#>   <chr>     <dbl>    <dbl>    <dbl> <dbl>          <dbl>
#> 1 xx            0        0        1     0              1
#> 2 yy            1        0        0     0              1
#> 3 zz            0        1        0     0              1
```

You’re right that inputting genes in a custom pathway with `.mut` doesn’t work properly. Maybe we can throw a warning for this? You can only enter a gene name bare (e.g. TP53) or gene_name.Amp/.Del/.fus (e.g. TP53.fus). 

I need to think on this more. Maybe we remove the option to calculate pathways by genes entirely? If not, we will work on cleaning up the current messaging.

**Comment by karissawhiting** [comment]
@hfuchs5 @michaelcurry1123 Do you have any ideas/preferences here?

**Comment by karissawhiting** [comment]
#289 
#286 

We have deprecated `count_pathways_by` functionality and require users specify .mut, .Del, .Amp in `custom_pathways` that they specify.
