### ISSUE TITLE
create_gene_binary: confusing documentation

### ISSUE THREAD

**Issue by hfuchs5** [MSKCC-Epi-Bio/gnomeR#252]
- [x] It’s unclear to me what “# mutations with mutation status marked as blank or NA were retained in the resulting binary matrix” means.  On a second look, I believe this is the mutation type (germline, somatic, etc.) – I think using “status” in the message, but “type” in the arguments is a little confusing. 
- [x] specify_panel argument is a little murky – is it saying there’s an option to make a binary matrix with any gene present in the MAF instead of restricting to a specific IMAPCT panel?  (i.e if we had TCGA data, it could make the binary matrix for the whole exome/genome sequencing instead of just genes on an IMPACT panel?) 

GENERAL question: How often do you come across data with both germline and somatic mutations?

**Comment by karissawhiting** [comment]
#260
