### ISSUE TITLE
vignette edits needed

### ISSUE THREAD

**Issue by hfuchs5** [MSKCC-Epi-Bio/gnomeR#254]
- [x] When talking about CNA formats, the “long format” and “wide format” definitions don’t need to be in code or have the scroll bar – it’s a little hard to read that way 

- [x] Under “Data Formats”, link for cBioPortal website isn’t displaying correctly 

- [x] In tbl_genomic() section, there is a line of code that isn’t rendered as “code font” (example for freq_cutoff) 

- [x] Add reference for oncogenic signaling pathways

**Comment by karissawhiting** [comment]
#260
