### ISSUE TITLE
summarize_by_gene VERY slow

### ISSUE THREAD

**Issue by hfuchs5** [MSKCC-Epi-Bio/gnomeR#259]

**Comment by michaelcurry1123** [comment]
create helper functions for gene percent cutoff

**Comment by hfuchs5** [comment]
function already ungroups before starting

Problem is the large size of the dataset and summarizing over it.

What do you think of an option in create_gene_binary that would strip the suffix off of cna/svs and then spit out the binary matrix that way?

**Comment by karissawhiting** [comment]
@hfuchs5 sorry I don't think I'm following! Could you give an example of the stripping off suffix?

**Comment by karissawhiting** [comment]
Side note: I find the [tictoc](https://cran.r-project.org/web/packages/tictoc/index.html) package really useful for testing speed!

**Comment by hfuchs5** [comment]
@karissawhiting 

I was thinking of something like having a summarize_by_gene = F default setting in create_gene_binary. When F it will run as normal, but if T, it will merge the mutation/cna/fusion datasets together and then make the binary dataset a matrix. Then we would transpose the matrix so that the gene names that were columns are now the row names (avoids pivot_longer). Then we could make the row names a column and mutate it so that all .Amp|.Del|.fus endings are removed. Then pipe to unique values only, and then transpose back to original format and pipe to as.data.frame().

**Comment by karissawhiting** [comment]
@hfuchs5 Thanks for thinking on this more!

I can see how this might speed things up but I do like the order/separation of the current pipeline of creating the full binary matrix, then summarizing it in an additional second step in terms of usability. If there is a significant increase in speed however, I'm open to a new set up. I propose we write some pseudo code for the options and then speed test some small examples before re-writing!
