### ISSUE TITLE
Add subset_by_panel() function

### ISSUE THREAD

**Issue by karissawhiting** [MSKCC-Epi-Bio/gnomeR#273]
If you need to remove newer genes for model fitting that needs no NAs

**Comment by hfuchs5** [comment]
read through the column names and only include those in a panel

**Comment by karissawhiting** [comment]
input is a panel ID. See `gnomeR::gene_panel` for panel IDs. Cross reference a colnames of binary matrix (`create_gene_binary()`) and subset just those genes. 

Maybe check aliases if colnames have any aliases (maybe throw warning?)
