### ISSUE TITLE
wishlist

### ISSUE THREAD

**Issue by mljaniczek** [MSKCC-Epi-Bio/gnomeR#3]
- [ ] TCGA pancan data prep

- [ ] Common checks and visualizations for TCGA pancan

- [ ]  Helper functions to prepare omic data for iCluster

- [ ]  Helper functions to visualize iCluster results

@karissawhiting @AxelitoMartin any others you want to add to wishlist?

**Comment by arorarshi** [comment]
taking the TCGA pancan data prep
