### ISSUE TITLE
Warning message from summarize_by_gene()

### ISSUE THREAD

**Issue by karissawhiting** [MSKCC-Epi-Bio/gnomeR#310]
`binary_matrix()` from example

![Screen Shot 2023-06-20 at 12 15 50 AM](https://github.com/MSKCC-Epi-Bio/gnomeR/assets/10888683/4e813a21-fb5a-4083-b4b2-7ea41f4f3fc8)

**Comment by hfuchs5** [comment]
could be because there's no na.rm arg in the max call. Could also be an issue with dplyr updates
