### ISSUE TITLE
adding panels for GENIE specifications

### ISSUE THREAD

**Issue by hfuchs5** [MSKCC-Epi-Bio/gnomeR#319]
UHN-555-PAN-GI-v1

UHN panels not included

**Comment by karissawhiting** [comment]
Right now all genie panels are included in gene_panels (https://github.com/MSKCC-Epi-Bio/gnomeR/blob/main/data-raw/gene_panels.R). Check if this is new or if it's just lower case v vs upper V.

**Comment by hfuchs5** [comment]
was just a capitalization issue and forgot to close out
