### ISSUE TITLE
Add travis CI and testthat code coverage

### ISSUE THREAD

**Issue by arorarshi** [MSKCC-Epi-Bio/gnomeR#47]

**Comment by karissawhiting** [comment]
Would love to schedule a meeting to watch you do this!

**Comment by arorarshi** [comment]
@AxelitoMartin are you getting a clean R CMD build or Ctrl+Shift+E in Rstudio? Travis will be a piece of cake then! Good to have this some what early, or a steady package check (Ctrl+Shift+E in Rstudio) before every commit.

**Comment by AxelitoMartin** [comment]
Don't know haven't tried yet. I am going to fix the binary matrix stuff first and reset the package at that point. Adding functions back in and doing check

**Comment by arorarshi** [comment]
fixed and tested!
