### ISSUE TITLE
Integrate with cbioPortal Web API to gnomeR

### ISSUE THREAD

**Issue by karissawhiting** [MSKCC-Epi-Bio/gnomeR#48]
I think a good start on this task will be to adjust the create.bin.matrix() function to accept column names other than MAF standard names as arguments. The MAF standards can be default.

**Comment by karissawhiting** [comment]
Here is the R API package: https://github.com/cBioPortal/cgdsr

I'm not sure if we need to actually wrap these functions or call them within gnomeR. We may just want to make sure the packages play nice by allowing gnomeR to easily ingest and clean the resulting API data.

Or, another option would be to just write our own light-weight API functions and bypass this package completely. 

@AxelitoMartin any thoughts?

**Comment by AxelitoMartin** [comment]
@karissawhiting How much work do you think it would be to write our own version?
I was thinking wrapper where people would provide DMPIDs + what kind of data they want (mutations, fusions, cna and/or facets). 
And then people could just pipe that into create binary matrix.
