### ISSUE TITLE
Review names of all functions and files

### ISSUE THREAD

**Issue by karissawhiting** [MSKCC-Epi-Bio/gnomeR#49]
Discussed doing a review of function names and file names. Here are some [tips](https://style.tidyverse.org/functions.html#naming) from the tidyverse style guide. 

For file names, we discussed changing file names to be same as function names when there is only one function in the file.

**Comment by AxelitoMartin** [comment]
karissawhiting assigned karissawhiting and AxelitoMartin and unassigned karissawhiting 
I thought this was you guys expertise haha
Also probably something we should change at the end

**Comment by karissawhiting** [comment]
Yea when I click on 'Assignees' it automatically assigned myself but I didn't mean to do that. I added you because you are the package owner/maintainer, but happy to work together on this! Also looping in @margarethannum the naming queen.

I think it might be good to deal with this earlier (before we build out the code base more) rather than later to limit potential renaming mishaps later.

**Comment by AxelitoMartin** [comment]
I will follow your lead ;)

**Comment by karissawhiting** [comment]
Here are some suggestions:

- currently `create.bin.matrix()` - could be  `make_binary_matrix()`, `create_binary_matrix()`, `make_bin_mat()`... something else?
- sub functions of the above could be: `create_mut_matrix()` /`make_mut_matrix()` etc...
- currently `dat.oncoPrint()` - `prep_oncoprint_data()`??
- currently `plot_oncoPrint()` - `plot_oncoprint()` 

Also, do you guys think it's okay that the function is actually returning a dataframe though the name suggests it is returning a matrix?
