### ISSUE TITLE
Review spe.palt argument in binary matrix function

### ISSUE THREAD

**Issue by karissawhiting** [MSKCC-Epi-Bio/gnomeR#50]
- [ ] Consider renaming
- [x] Throw a warning when spe.palt = FALSE if there are multiple platforms detected

For the second item, we can look at the patient ID's IMX codes to tell if there are multiple platforms.

**Comment by AxelitoMartin** [comment]
Agreed name could be better
Now argument will be overwritten if all IDs are not from IMPACT or if there is a single platform
