### ISSUE TITLE
Change the way mutation status argument is dealt with- soft check and warning for SOMATIC mutation status.

### ISSUE THREAD

**Issue by karissawhiting** [MSKCC-Epi-Bio/gnomeR#51]
@arorarshi or @AxelitoMartin can you add description and a reprex to this issue?

**Comment by arorarshi** [comment]
There is a soft check for this column, and now we issue a warning with the following message - 
>The MAF file inputted is missing a mutation status column (Mutation_Status). It will be assumed that all variants are of the same type (SOMATIC/GERMLINE)
Earlier it used to be an error, but not all MAF files have a Mutation_Status column.
