### ISSUE TITLE
Add a check for genes that are in user-provided MAF but not in IMPACT panel gene list

### ISSUE THREAD

**Issue by karissawhiting** [MSKCC-Epi-Bio/gnomeR#54]
Thrown an error if a gene isn't part of any IMPACT platform. Additionally, there should be a check for any genes that have been renamed.

The check should probably be based off list from issue #53

**Comment by arorarshi** [comment]
If sample IDs are not ending with __IM__ then  `spe.plat` is set to `FASLE`. By default its is `FALSE   `

**Comment by edrill** [comment]
IMPACT HEME samples end in IH.
There are many IMPACT HEME panel genes that are not included in solid
IMPACT versions.
Do you want to include these in gnomer package?
