### ISSUE TITLE
Create {pkgdown} website

### ISSUE THREAD

**Issue by karissawhiting** [MSKCC-Epi-Bio/gnomeR#56]
Create a package website

@margarethannum

**Comment by mljaniczek** [comment]
- [ ] Update DESCRIPTION file. Names of authors, Title and Description fields

- [ ] Run `usethis::use_testthat()` to start us off with a testing environment

- [ ] Run `usethis::use_spell_check`, fix spelling and make a WORDLIST. 

- [ ] Expand README

- [ ] Initialize website

**Comment by mljaniczek** [comment]
- [ ] Run checks. When documenting, several functions had missing description for parameters (e.g. maf-oncokb-annotator.R file, param `maf` did not have a description.
