### ISSUE TITLE
Some imports should be moved to suggests?

### ISSUE THREAD

**Issue by mljaniczek** [MSKCC-Epi-Bio/gnomeR#57]
Several imports are in the package that I'm not sure are necessary. 

Imports should be reserved for packages whose functions we need to do our functions. 

For example: 
ComplexHeatmap
GGally
plotly 

Do we actually use functions from these packages within any of our functions? If so, they should clearly be marked within our functions as `ComplexHeatmap::add_heatmap` (should never just be "naked" like `add_heatmap`). But, I don't see functions from these packages being called this way anywhere in the package. 

To make the package "leaner" I would recommend we cut down on unnecessary imports, or else make more clear why we require these inputs! 

@AxelitoMartin @arorarshi @karissawhiting any thoughts on this?

**Comment by mljaniczek** [comment]
When I run the package checks I get this error: 
> checking package dependencies ... ERROR
  Namespace dependencies not required:
    'GGally', 'RColorBrewer', 'gplots', 'lattice', 'reshape2', 'stringr',
    'survival', 'survminer'
  
So I think that means this can safely be deleted as dependencies for now...

**Comment by arorarshi** [comment]
I think we can close this issue?

**Comment by AxelitoMartin** [comment]
Yes indeed
