### ISSUE TITLE
CNA events - process and analysis 

### ISSUE THREAD

**Issue by arorarshi** [MSKCC-Epi-Bio/gnomeR#81]
__Processing CNA files__ 
1. Have the gene columns as `gene_CN` and then have the discrete states as is. Have an option to also return CN events as binary. (This can be in `make-bin-mat.R ` or `make-oncoprint-dat.R`)
2. In `cna` file, there are no NA, even if the sample was sequenced on a different platform for a gene that didn't exist in the platform. (Find out)
3. What type of an event is -1.5 in CN? Maybe there is a new file for CN (Find out) 

__Analysis__
4. Analyze Copy Number Alterations (CNA) wrt to an entire gene and perform association test on all observed CN states of the gene

**Comment by AxelitoMartin** [comment]
Data can be created with factors but definitely needs some testing
