### ISSUE TITLE
Update oncoprint function to properly deal with NAs

### ISSUE THREAD

**Issue by karissawhiting** [MSKCC-Epi-Bio/gnomeR#88]
Two options:

- Show missing as explicit factor level (and calculate percentages with this as a separate group)
- Omit NAs (like cbioportal oncoprints do)

@arorarshi @AxelitoMartin

**Comment by karissawhiting** [comment]
I think this is done? Can we close? @arorarshi

**Comment by AxelitoMartin** [comment]
Yep we added this
